trigger:
  - develop

variables:
  dockerRegistry: 'devopsaiagent.azurecr.io'
  imageName: 'frappe'
  imageTag: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Push Frappe image to ACR'
            inputs:
              command: 'build'
              Dockerfile: 'Dockerfile'
              repository: '$(imageName)'
              dockerfile: $(Build.SourcesDirectory)/Dockerfile
              tags: |
                $(imageTag)
                latest
              arguments: '--build-arg BUILDKIT_INLINE_CACHE=1'

  - stage: DeployToAKS
    jobs:
      - job: DeployToAKS
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          
          - task: KubernetesManifest@0
            displayName: 'Deploy to AKS'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'AKS-ServiceConnection'
              namespace: 'default'
              manifests: |
                $(Build.SourcesDirectory)/k8s/deployment.yaml
